import React from 'react'
import Navbarcomp from './Navbar'
import '../pages/styles/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
  <> <Navbarcomp />

  <div className="bg-gradient-to-br from-white to-pink-200 items-center justify-center h-full">
  {children}
  </div>
  </>
  )
}
